### ISSUE TITLE
GetServiceAsync(typeof(IVsSolution))?

### ISSUE THREAD

**Issue by jcansdale** [madskristensen/SolutionLoadSample#2]
https://github.com/madskristensen/SolutionLoadSample/blob/master/src/VSPackage.cs#L39

I wondered if this should be  `await GetServiceAsync(typeof(SVsSolution)) as IVsSolution` rather than `typeof(IVsSolution)`? I'm guessing it probably doesn't matter.

Sorry about the drive-by issue. 😉

**Comment by madskristensen** [comment]
It doesn't matter it seems like, but for GitHub or Google searches it does. Let me switch to SVsSolution like you suggested
